const PDFDocument = require('pdfkit');

const buildIncidentReportPdf = ({ result, aiReport }) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const chunks = [];

    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const analysis = result.analysis || {};
    const prediction = analysis.prediction || {};
    const entropy = analysis.entropy || {};
    const sectionEntropy = entropy.section_entropy || {};
    const iat = analysis.iat_analysis || {};
    const regexScan = analysis.regex_scan || {};
    const dynamicAnalysis = (result.combinedIntelligence || {}).dynamic_analysis || {};
    const dynamicMetadata = dynamicAnalysis.metadata || {};
    const networkIndicators = dynamicAnalysis.network_indicators || {};
    const fileSystemImpact = dynamicAnalysis.file_system_impact || {};
    const processTree = dynamicAnalysis.process_tree || {};

    doc.fontSize(22).fillColor('#0f172a').text('ViperLens');
    doc.moveDown(0.2);
    doc.fontSize(14).fillColor('#334155').text('Security Incident Report');
    doc.moveDown();

    doc.fontSize(11).fillColor('#0f172a');
    doc.text(`Date: ${new Date().toISOString()}`);
    doc.text(`File: ${result.fileName || 'Unknown'}`);
    doc.text(`Stored As: ${result.storedAs || 'Unknown'}`);
    doc.text(`Verdict: ${prediction.label || analysis.verdict || 'Unknown'}`);
    doc.text(`Confidence: ${prediction.confidence || 0}`);
    doc.moveDown();

    doc.fontSize(13).fillColor('#0f172a').text('Static Analysis Summary');
    doc.moveDown(0.4);
    doc.fontSize(11).fillColor('#1e293b');
    doc.text(`Packing Alert: ${entropy.packing_alert ? 'Yes' : 'No'}`);
    doc.text(`Total Imports: ${iat.total_imports || 0}`);
    doc.text(`Suspicious APIs: ${(iat.suspicious_apis || []).join(', ') || 'None'}`);
    doc.moveDown();

    doc.fontSize(13).fillColor('#0f172a').text('Section Entropy');
    doc.moveDown(0.3);
    Object.entries(sectionEntropy).forEach(([section, value]) => {
      doc.fontSize(10).fillColor('#1e293b').text(`${section}: ${value}`);
    });
    doc.moveDown();

    doc.fontSize(13).fillColor('#0f172a').text('Regex Matches');
    doc.moveDown(0.3);
    doc.fontSize(10).fillColor('#1e293b').text(`IPv4: ${(regexScan.ipv4_matches || []).join(', ') || 'None'}`);
    doc.fontSize(10).fillColor('#1e293b').text(`URLs: ${(regexScan.url_matches || []).join(', ') || 'None'}`);
    doc.moveDown();

    doc.fontSize(13).fillColor('#0f172a').text('Falcon Sandbox Report');
    doc.moveDown(0.3);
    doc.fontSize(10).fillColor('#1e293b').text(`Status: ${dynamicMetadata.status || 'Not available'}`);
    doc.fontSize(10).fillColor('#1e293b').text(`Threat Score: ${dynamicMetadata.threat_score || 'Not available'}`);
    doc.fontSize(10).fillColor('#1e293b').text(`MITRE Matches: ${JSON.stringify(dynamicMetadata.mitre_attck_framework_matches || [])}`);
    doc.fontSize(10).fillColor('#1e293b').text(`Signatures: ${JSON.stringify(dynamicMetadata.signatures || [])}`);
    doc.fontSize(10).fillColor('#1e293b').text(`Network Indicators: ${JSON.stringify(networkIndicators.connections || [])}`);
    doc.fontSize(10).fillColor('#1e293b').text(`C&C API Evidence: ${JSON.stringify(networkIndicators.preserved_cc_calls || [])}`);
    doc.fontSize(10).fillColor('#1e293b').text(`File System Impact: ${JSON.stringify(fileSystemImpact.changed_paths || [])}`);
    doc.fontSize(10).fillColor('#1e293b').text(`Process Tree Nodes: ${processTree.total_nodes || 0}`);
    doc.moveDown();

    if (aiReport && aiReport.content) {
      doc.fontSize(13).fillColor('#0f172a').text('Gemini Analyst Advice');
      doc.moveDown(0.3);
      doc.fontSize(10).fillColor('#1e293b').text(aiReport.content, {
        width: 500,
        align: 'left'
      });
      doc.moveDown(0.5);
      doc.fontSize(9).fillColor('#64748b').text(`Generated by: ${aiReport.model || 'Gemini'} at ${aiReport.generatedAt || 'N/A'}`);
    }

    doc.end();
  });
};

module.exports = {
  buildIncidentReportPdf
};
